on:
  push:
    branches:
      - '**'

name: CI

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Check
        run: |
          npm install
          npm run lint
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Test
        run: |
          npm install
          npm run build